export enum GameActionType {
   
    ADD_EVENT_BUTTON = 'ADD_EVENT_BUTTON',
    SAVE_GAME_EVENT = 'SAVE_GAME_EVENT',
    GET_GAME_EVENT = 'GET_GAME_EVENT',
    SELECTED_GAME_EVENT = 'SELECTED_GAME_EVENT'
}