export enum PlayerActionType {

    ADD_USERS = 'ADD_USERS',
    ADD_USER_INFO = 'ADD_USER_INFO',
    UPDATE_USER_INFO = 'UPDATE_USER_INFO',
    ADD_PLAYER_INFO = 'ADD_PLAYER_INFO',
    ADD_ACTIVE_PLAYER = 'ADD_ACTIVE_PLAYER',
    REMOVE_ACTIVE_PLAYER = 'REMOVE_ACTIVE_PLAYER',
    UPDATE_PLAYER_INFO = 'UPDATE_PLAYER_INFO',
    USER_INFO = 'USER_INFO',
    CLEAR_ALL_DATA_USER = 'CLEAR_ALL_DATA_USER',
    OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE',
    CLOSE_EDIT_PROFILE = 'CLOSE_EDIT_PROFILE',
    ADD_PEOPLE_INFO = 'ADD_PEOPLE_INFO',
    HAS_MORE_DATA_PEOPLE = 'HAS_MORE_DATA_PEOPLE',
    NOT_MORE_DATA_PEOPLE = 'NOT_MORE_DATA_PEOPLE',
    REQUEST_PAGE_PEOPLE = 'REQUEST_PAGE_PEOPLE',
    LAST_USER_PEOPLE = 'LAST_POST_PEOPLE'
}
